#! /usr/bin/env python
import random, sys

male_first = {
    "James",
    "Robert",
    "John",
    "Michael",
    "David",
    "William",
    "Richard",
    "Joseph",
    "Thomas",
    "Charles",
    "Christopher",
    "Daniel",
    "Matthew",
    "Anthony",
    "Mark",
    "Donald",
    "Steven",
    "Paul",
    "Andrew",
    "Joshua",
    "Kenneth",
    "Kevin",
    "Brian",
    "George",
    "Timothy",
    "Ronald",
    "Edward",
    "Jason",
    "Jeffrey",
    "Ryan",
    "Jacob",
    "Gary",
    "Nicholas",
    "Eric",
    "Jonathan",
    "Stephen",
    "Larry",
    "Justin",
    "Scott",
    "Brandon",
    "Benjamin",
    "Samuel",
    "Gregory",
    "Alexander",
    "Frank",
    "Patrick",
    "Raymond",
    "Jack",
    "Dennis",
    "Jerry",
    "Tyler",
    "Aaron",
    "Jose",
    "Adam",
    "Nathan",
    "Henry",
    "Douglas",
    "Zachary",
    "Peter",
    "Kyle",
    "Ethan",
    "Walter",
    "Noah",
    "Jeremy",
    "Christian",
    "Keith",
    "Roger",
    "Terry",
    "Gerald",
    "Harold",
    "Sean",
    "Austin",
    "Carl",
    "Arthur",
    "Lawrence",
    "Dylan",
    "Jesse",
    "Jordan",
    "Bryan",
    "Billy",
    "Joe",
    "Bruce",
    "Gabriel",
    "Logan",
    "Albert",
    "Willie",
    "Alan",
    "Juan",
    "Wayne",
    "Elijah",
    "Randy",
    "Roy",
    "Vincent",
    "Ralph",
    "Eugene",
    "Russell",
    "Bobby",
    "Mason",
    "Philip",
    "Louis",
}
female_first = {
    "Mary",
    "Patricia",
    "Jennifer",
    "Linda",
    "Elizabeth",
    "Barbara",
    "Susan",
    "Jessica",
    "Sarah",
    "Karen",
    "Lisa",
    "Nancy",
    "Betty",
    "Margaret",
    "Sandra",
    "Ashley",
    "Kimberly",
    "Emily",
    "Donna",
    "Michelle",
    "Carol",
    "Amanda",
    "Dorothy",
    "Melissa",
    "Deborah",
    "Stephanie",
    "Rebecca",
    "Sharon",
    "Laura",
    "Cynthia",
    "Kathleen",
    "Amy",
    "Angela",
    "Shirley",
    "Anna",
    "Brenda",
    "Pamela",
    "Emma",
    "Nicole",
    "Helen",
    "Samantha",
    "Katherine",
    "Christine",
    "Debra",
    "Rachel",
    "Carolyn",
    "Janet",
    "Catherine",
    "Maria",
    "Heather",
    "Diane",
    "Ruth",
    "Julie",
    "Olivia",
    "Joyce",
    "Virginia",
    "Victoria",
    "Kelly",
    "Lauren",
    "Christina",
    "Joan",
    "Evelyn",
    "Judith",
    "Megan",
    "Andrea",
    "Cheryl",
    "Hannah",
    "Jacqueline",
    "Martha",
    "Gloria",
    "Teresa",
    "Ann",
    "Sara",
    "Madison",
    "Frances",
    "Kathryn",
    "Janice",
    "Jean",
    "Abigail",
    "Alice",
    "Julia",
    "Judy",
    "Sophia",
    "Grace",
    "Denise",
    "Amber",
    "Doris",
    "Marilyn",
    "Danielle",
    "Beverly",
    "Isabella",
    "Theresa",
    "Diana",
    "Natalie",
    "Brittany",
    "Charlotte",
    "Marie",
    "Kayla",
    "Alexis",
    "Lori",
}
family_names = {
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzales",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Gutierrez",
    "Ortiz",
    "Morgan",
    "Cooper",
    "Peterson",
    "Bailey",
    "Reed",
    "Kelly",
    "Howard",
    "Ramos",
    "Kim",
    "Cox",
    "Ward",
    "Richardson",
    "Watson",
    "Brooks",
    "Chavez",
    "Wood",
    "James",
    "Bennet",
    "Gray",
    "Mendoza",
    "Ruiz",
    "Hughes",
    "Price",
    "Alvarez",
    "Castillo",
    "Sanders",
    "Patel",
    "Myers",
    "Long",
    "Ross",
    "Foster",
    "Jimenez",
}


def get_name():
    name = ""
    random.seed()
    gender = random.getrandbits(1)
    if gender:
        name += male_first.pop()
        male_first.add(name)
    else:
        name += female_first.pop()
        female_first.add(name)
    middle_chooser = random.randint(0, 10)
    if middle_chooser < 4:
        if gender:
            mid = male_first.pop()
            male_first.add(mid)
            name += " " + mid
        else:
            mid = female_first.pop()
            female_first.add(mid)
            name += " " + mid
    elif middle_chooser < 6:
        if gender:
            mid = female_first.pop()
            female_first.add(mid)
            name += " " + mid
        else:
            mid = male_first.pop()
            male_first.add(mid)
            name += " " + mid
    elif middle_chooser < 7:
        if gender:
            mid1 = male_first.pop()
            mid2 = male_first.pop()
            male_first.add(mid1)
            male_first.add(mid2)
            name += " " + mid1 + mid2
        else:
            mid1 = female_first.pop()
            mid2 = female_first.pop()
            female_first.add(mid1)
            female_first.add(mid2)
            name += " " + mid1 + mid2
    elif middle_chooser < 8:
        last_for_mid = family_names.pop()
        family_names.add(last_for_mid)
        name += " " + last_for_mid
    clan = family_names.pop()
    family_names.add(clan)
    name += " " + clan
    return name
